import { existsSync, writeFileSync } from "fs";
import { Jimp } from "jimp";
import { box as kogaBox } from "../src/data/guide/koga";
import { box } from "../src/data/guide/victoryRoad";
import { type Box, getCanon, resolveBox } from "../src/utils/box";
import { resolvePokemon } from "../src/utils/pokemon";

const SPRITE_BASE = "https://raw.githubusercontent.com/Autumnchi/coloured-home-sprites/main/";

function rgbToHsl(r: number, g: number, b: number): [number, number, number] {
  r /= 255;
  g /= 255;
  b /= 255;
  const max = Math.max(r, g, b),
    min = Math.min(r, g, b);
  const l = (max + min) / 2;
  if (max === min) return [0, 0, l];
  const d = max - min;
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  let h = 0;
  if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
  else if (max === g) h = ((b - r) / d + 2) / 6;
  else h = ((r - g) / d + 4) / 6;
  return [h, s, l];
}

function hslToRgb(h: number, s: number, l: number): [number, number, number] {
  if (s === 0) {
    const v = Math.round(l * 255);
    return [v, v, v];
  }
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
  const p = 2 * l - q;
  const hue2rgb = (t: number) => {
    if (t < 0) t += 1;
    if (t > 1) t -= 1;
    if (t < 1 / 6) return p + (q - p) * 6 * t;
    if (t < 1 / 2) return q;
    if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
    return p;
  };
  return [
    Math.round(hue2rgb(h + 1 / 3) * 255),
    Math.round(hue2rgb(h) * 255),
    Math.round(hue2rgb(h - 1 / 3) * 255),
  ];
}

const TARGET_L = 0.45;

function dominantColor(pixels: Buffer): string {
  const buckets: Record<string, { r: number; g: number; b: number; score: number }> = {};
  for (let i = 0; i < pixels.length; i += 4) {
    const r = pixels[i],
      g = pixels[i + 1],
      b = pixels[i + 2],
      a = pixels[i + 3];
    if (a < 128) continue;
    const brightness = (r + g + b) / 3;
    if (brightness > 230 || brightness < 40) continue;
    const qr = Math.min(255, Math.round(r / 24) * 24);
    const qg = Math.min(255, Math.round(g / 24) * 24);
    const qb = Math.min(255, Math.round(b / 24) * 24);
    const key = `${qr},${qg},${qb}`;
    const max = Math.max(qr, qg, qb);
    const sat = max === 0 ? 0 : (max - Math.min(qr, qg, qb)) / max;
    if (!buckets[key]) buckets[key] = { r: qr, g: qg, b: qb, score: 0 };
    buckets[key].score += sat * sat + 0.05;
  }
  let best = { r: 128, g: 128, b: 128, score: -1 };
  for (const b of Object.values(buckets)) {
    if (b.score > best.score) best = b;
  }
  const [h, s, l] = rgbToHsl(best.r, best.g, best.b);
  const normalizedL = s < 0.1 ? l : TARGET_L; // leave grays as-is
  const [r, g, b] = hslToRgb(h, s, normalizedL);
  return `rgb(${r},${g},${b})`;
}

function buildEntries(resolvedBox: ReturnType<typeof resolveBox>) {
  const canon = getCanon(resolvedBox);
  const entries: { canonName: string; spriteKey?: string }[] = [];
  const seen = new Set<string>();
  for (const pokemon of resolvedBox.pokemon) {
    const p = resolvePokemon(pokemon);
    const canonName = canon(p.name);
    if (seen.has(canonName)) continue;
    seen.add(canonName);
    entries.push({ canonName, spriteKey: p.spriteKey });
  }
  entries.sort((a, b) => a.canonName.localeCompare(b.canonName));
  return entries;
}

async function fetchColors(
  entries: { canonName: string; spriteKey?: string }[],
  existing: Record<string, string> = {}
): Promise<Record<string, string>> {
  const colors: Record<string, string> = { ...existing };
  const toFetch = entries.filter((e) => !colors[e.canonName]);
  if (toFetch.length) console.log(`Fetching colors for ${toFetch.length} Pokémon...`);
  for (const { canonName, spriteKey } of toFetch) {
    const url = `${SPRITE_BASE}${(spriteKey ?? canonName).toLowerCase()}.png`;
    try {
      const buf = await fetch(url).then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.arrayBuffer();
      });
      const image = await Jimp.read(Buffer.from(buf));
      image.resize({ w: 48, h: 48 });
      colors[canonName] = dominantColor(image.bitmap.data as unknown as Buffer);
      console.log(`  ✓ ${canonName}: ${colors[canonName]}`);
    } catch (e) {
      colors[canonName] = "rgb(128,128,128)";
      console.warn(`  ✗ ${canonName}: ${e}`);
    }
  }
  return colors;
}

function writeOutput(
  path: string,
  entries: { canonName: string }[],
  colors: Record<string, string>
) {
  const lines = entries.map(({ canonName }) => `  "${canonName}": "${colors[canonName]}",`);
  const output = `// Generated by scripts/sprite-colors.ts — re-run to update\nexport const SPRITE_COLORS: Record<string, string> = {\n${lines.join("\n")}\n};\n`;
  writeFileSync(path, output);
  console.log(`Wrote ${path}`);
}

(async () => {
  const baseEntries = buildEntries(resolveBox(box));
  const colors = await fetchColors(baseEntries);
  writeOutput("src/data/spriteColors.ts", baseEntries, colors);

  const secretMode =
    process.env.SECRET_MODE === "true" && existsSync("src/data/guide/eliteFourSecrets.enabled.ts");

  if (secretMode) {
    console.log("\nGenerating secret sprite colors...");

    // Chain each enabled secrets function starting from the stub koga box.
    // Each function adds the real secret Pokémon (including evolutions) on top.
    const { getKogaSecrets } = await import("../src/data/guide/kogaSecrets.enabled.ts");
    const { getBlaineSecrets } = await import("../src/data/guide/blaineSecrets.enabled.ts");
    const { getClairSecrets } = await import("../src/data/guide/clairSecrets.enabled.ts");
    const { getVictoryRoadSecrets } =
      await import("../src/data/guide/victoryRoadSecrets.enabled.ts");
    const { getEliteFourSecrets } = await import("../src/data/guide/eliteFourSecrets.enabled.ts");

    const chain = [
      getKogaSecrets,
      getBlaineSecrets,
      getClairSecrets,
      getVictoryRoadSecrets,
      getEliteFourSecrets,
    ];
    let secretBox: Box = kogaBox;
    for (const fn of chain) {
      ({ box: secretBox } = fn(secretBox));
    }

    const secretEntries = buildEntries(resolveBox(secretBox));
    const secretColors = await fetchColors(secretEntries, colors);
    writeOutput("src/data/spriteColors.enabled.ts", secretEntries, secretColors);
  }
})();
