import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  guideSidebar: [{ type: "autogenerated", dirName: "." }],
  dataSidebar: [{ type: "autogenerated", dirName: "." }],
  overlaySidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
