export const POKEMON_ABBREVIATIONS: Record<string, string> = {
  "Farfetch'd": "Farfetch’d",
  // Alola (-A)
  "Diglett-A": "Diglett-Alola",
  "Dugtrio-A": "Dugtrio-Alola",
  "Exeggutor-A": "Exeggutor-Alola",
  "Geodude-A": "Geodude-Alola",
  "Golem-A": "Golem-Alola",
  "Graveler-A": "Graveler-Alola",
  "Grimer-A": "Grimer-Alola",
  "Marowak-A": "Marowak-Alola",
  "Meowth-A": "Meowth-Alola",
  "Muk-A": "Muk-Alola",
  "Ninetales-A": "Ninetales-Alola",
  "Persian-A": "Persian-Alola",
  "Pikachu-A": "Pikachu-Alola",
  "Raichu-A": "Raichu-Alola",
  "Raticate-A": "Raticate-Alola",
  "Rattata-A": "Rattata-Alola",
  "Sandshrew-A": "Sandshrew-Alola",
  "Sandslash-A": "Sandslash-Alola",
  "Vulpix-A": "Vulpix-Alola",
  // Galar (-G)
  "Articuno-G": "Articuno-Galar",
  "Corsola-G": "Corsola-Galar",
  "Darmanitan-G": "Darmanitan-Galar",
  "Darmanitan-GZ": "Darmanitan-Galar-Zen",
  "Darumaka-G": "Darumaka-Galar",
  "Farfetch'd-G": "Farfetch\u2019d-Galar",
  "Linoone-G": "Linoone-Galar",
  "Meowth-G": "Meowth-Galar",
  "Moltres-G": "Moltres-Galar",
  "Mr. Mime-G": "Mr. Mime-Galar",
  "Ponyta-G": "Ponyta-Galar",
  "Rapidash-G": "Rapidash-Galar",
  "Slowbro-G": "Slowbro-Galar",
  "Slowking-G": "Slowking-Galar",
  "Slowpoke-G": "Slowpoke-Galar",
  "Stunfisk-G": "Stunfisk-Galar",
  "Weezing-G": "Weezing-Galar",
  "Yamask-G": "Yamask-Galar",
  "Zapdos-G": "Zapdos-Galar",
  "Zigzagoon-G": "Zigzagoon-Galar",
  // Hisui (-H)
  "Arcanine-H": "Arcanine-Hisui",
  "Avalugg-H": "Avalugg-Hisui",
  "Braviary-H": "Braviary-Hisui",
  "Decidueye-H": "Decidueye-Hisui",
  "Electrode-H": "Electrode-Hisui",
  "Goodra-H": "Goodra-Hisui",
  "Growlithe-H": "Growlithe-Hisui",
  "Lilligant-H": "Lilligant-Hisui",
  "Qwilfish-H": "Qwilfish-Hisui",
  "Samurott-H": "Samurott-Hisui",
  "Sliggoo-H": "Sliggoo-Hisui",
  "Sneasel-H": "Sneasel-Hisui",
  "Typhlosion-H": "Typhlosion-Hisui",
  "Voltorb-H": "Voltorb-Hisui",
  "Zoroark-H": "Zoroark-Hisui",
  "Zorua-H": "Zorua-Hisui",
  // Paldea (-P)
  "Wooper-P": "Wooper-Paldea",
  "Tauros-PA": "Tauros-Paldea-Aqua",
  "Tauros-PB": "Tauros-Paldea-Blaze",
  "Tauros-PC": "Tauros-Paldea-Combat",
  // Origin (-O) and Primal (-P)
  "Dialga-O": "Dialga-Origin",
  "Dialga-P": "Dialga-Primal",
  "Giratina-O": "Giratina-Origin",
  "Groudon-P": "Groudon-Primal",
  "Kyogre-P": "Kyogre-Primal",
  "Palkia-O": "Palkia-Origin",
  // Mega with X/Y variants
  "Charizard-MegaX": "Charizard-Mega-X",
  "Charizard-MegaY": "Charizard-Mega-Y",
  "Mewtwo-MegaX": "Mewtwo-Mega-X",
  "Mewtwo-MegaY": "Mewtwo-Mega-Y",
  // Other special forms
  "Aegislash-B": "Aegislash-Blade",
  "Aegislash-S": "Aegislash-Shield",
  "Calyrex-I": "Calyrex-Ice",
  "Calyrex-S": "Calyrex-Shadow",
  "Cramorant-Gorg": "Cramorant-Gorging",
  "Cramorant-Gulp": "Cramorant-Gulping",
  "Darmanitan-Z": "Darmanitan-Zen",
  "Deoxys-A": "Deoxys-Attack",
  "Deoxys-D": "Deoxys-Defense",
  "Deoxys-S": "Deoxys-Speed",
  "Enamorus-I": "Enamorus",
  "Enamorus-T": "Enamorus-Therian",
  "Eternatus-Max": "Eternatus-Eternamax",
  "Hoopa-U": "Hoopa-Unbound",
  "Kyurem-B": "Kyurem-Black",
  "Kyurem-W": "Kyurem-White",
  "Landorus-I": "Landorus",
  "Landorus-T": "Landorus-Therian",
  "Lycanroc-D": "Lycanroc-Dusk",
  "Lycanroc-M": "Lycanroc-Midnight",
  "Necrozma-DM": "Necrozma-Dusk-Mane",
  "Necrozma-DW": "Necrozma-Dawn-Wings",
  "Ogerpon-C": "Ogerpon-Cornerstone",
  "Ogerpon-H": "Ogerpon-Hearthflame",
  "Ogerpon-W": "Ogerpon-Wellspring",
  "Scream Tail": "Screamtail",
  "Squawkabilly-G": "Squawkabilly",
  "Thundurus-I": "Thundurus",
  "Thundurus-T": "Thundurus-Therian",
  "Tornadus-I": "Tornadus",
  "Tornadus-T": "Tornadus-Therian",
  "Toxtricity-LK": "Toxtricity-Low-Key",
  "Ursaluna-BM": "Ursaluna-Bloodmoon",
  "Urshifu-R": "Urshifu-Rapid-Strike",
  "Urshifu-S": "Urshifu",
  "Wormadam-S": "Wormadam-Sandy",
  "Wormadam-T": "Wormadam-Trash",
  "Zacian-C": "Zacian-Crowned",
  "Zamazenta-C": "Zamazenta-Crowned",
  "Zygarde-10": "Zygarde-10%",
  "Zygarde-C": "Zygarde-Complete",
};

export const MOVE_ABBREVIATIONS: Record<string, string> = {
  "Behem. Blade": "Behemoth Blade",
  "Bleak. Storm": "Bleakwind Storm",
  "Burn. Bulwark": "Burning Bulwark",
  "Burn. Jealousy": "Burning Jealousy",
  "Cease. Edge": "Ceaseless Edge",
  "Chilly Recept.": "Chilly Reception",
  "Clang. Scales": "Clanging Scales",
  "Clang. Soul": "Clangorous Soul",
  "Dazz. Gleam": "Dazzling Gleam",
  "Diam. Storm": "Diamond Storm",
  "Disarm. Voice": "Disarming Voice",
  "Double I. Bash": "Double Iron Bash",
  "Dragon Hamm.": "Dragon Hammer",
  "Dyna. Cannon": "Dynamax Cannon",
  "Dynam. Punch": "Dynamic Punch",
  "Elect. Terrain": "Electric Terrain",
  "Expand. Force": "Expanding Force",
  "False Surrend.": "False Surrender",
  "First Impress.": "First Impression",
  "Giga. Hammer": "Gigaton Hammer",
  "Headlon. Rush": "Headlong Rush",
  "High Horsep.": "High Horsepower",
  "High J. Kick": "High Jump Kick",
  "HP Bug": "Hidden Power Bug",
  "HP Dark": "Hidden Power Dark",
  "HP Dragon": "Hidden Power Dragon",
  "HP Electric": "Hidden Power Electric",
  "HP Fighting": "Hidden Power Fighting",
  "HP Fire": "Hidden Power Fire",
  "HP Flying": "Hidden Power Flying",
  "HP Ghost": "Hidden Power Ghost",
  "HP Grass": "Hidden Power Grass",
  "HP Ground": "Hidden Power Ground",
  "HP Ice": "Hidden Power Ice",
  "HP Poison": "Hidden Power Poison",
  "HP Psychic": "Hidden Power Psychic",
  "HP Rock": "Hidden Power Rock",
  "HP Steel": "Hidden Power Steel",
  "HP Water": "Hidden Power Water",
  "Hypersp. Fury": "Hyperspace Fury",
  "Hypersp. Hole": "Hyperspace Hole",
  "Matcha Got.": "Matcha Gotcha",
  "Misty Explosi.": "Misty Explosion",
  "Parab. Charge": "Parabolic Charge",
  "Popula. Bomb": "Population Bomb",
  "Pow-Up Punch": "Power-Up Punch",
  "Precip. Blades": "Precipice Blades",
  "Prism. Laser": "Prismatic Laser",
  "Psych. Terrain": "Psychic Terrain",
  "Revel. Dance": "Revelation Dance",
  "Revival Bless.": "Revival Blessing",
  "Scorch. Sands": "Scorching Sands",
  "Spring. Storm": "Springtide Storm",
  "Steam Erupt.": "Steam Eruption",
  "Stom. Tantrum": "Stomping Tantrum",
  "Surg. Strikes": "Surging Strikes",
  "Thous. Arrows": "Thousand Arrows",
  "Thund. Kick": "Thunderous Kick",
  "Water Shurik.": "Water Shuriken",
  "Wild. Storm": "Wildbolt Storm",
};

export const ITEM_ABBREVIATIONS: Record<string, string> = {
  "Corner. Mask": "Cornerstone Mask",
  "HeavyD. Boots": "Heavy-Duty Boots",
  "Hearth. Mask": "Hearthflame Mask",
  "Terrain Extend.": "Terrain Extender",
  "Weakness Pol.": "Weakness Policy",
  "Well. Mask": "Wellspring Mask",
};

export const resolveItem = (name: string): string => ITEM_ABBREVIATIONS[name] ?? name;

export const resolveSpecies = (name: string): string => POKEMON_ABBREVIATIONS[name] ?? name;

export const resolveMove = (name: string): string => MOVE_ABBREVIATIONS[name] ?? name;
