import { Pokemon } from "@site/src/components/Team";

export const route22RivalTeam: Pokemon[] = [
  {
    name: "Snubbull",
    level: 15,
    nature: "Adamant",
    ability: "Intimidate",
    item: "Muscle Band",
    move1: "Pow-Up Punch",
    move2: "Covet",
    move3: "Thunder Wave",
    move4: "Fire Fang",
  },
  {
    name: "Litleo",
    level: 15,
    nature: "Timid",
    ability: "Rivalry",
    item: "Wise Glasses",
    move1: "Incinerate",
    move2: "Round",
    move3: "HP Grass",
    move4: "Sleep Talk",
  },
  {
    name: "Squirtle",
    level: 16,
    nature: "Adamant",
    ability: "Torrent",
    item: "Oran Berry",
    move1: "Pow-Up Punch",
    move2: "Aqua Jet",
    move3: "Rock Tomb",
    move4: "Curse",
  },
];

export const viridianForestBrendanTeam: Pokemon[] = [
  {
    name: "Meditite",
    level: 14,
    nature: "Adamant",
    ability: "Pure Power",
    item: "Muscle Band",
    move1: "Fake Out",
    move2: "Rock Smash",
    move3: "Bullet Punch",
    move4: "Rock Tomb",
  },
  {
    name: "Corphish",
    level: 15,
    nature: "Adamant",
    ability: "Adaptability",
    item: "Mystic Water",
    move1: "Aqua Jet",
    move2: "Aerial Ace",
    move3: "Rock Tomb",
    move4: "Knock Off",
  },
  {
    name: "Numel",
    level: 15,
    nature: "Lonely",
    ability: "Simple",
    item: "Passho Berry",
    move1: "Ancient Power",
    move2: "Flame Charge",
    move3: "Rock Tomb",
    move4: "Bulldoze",
  },
  {
    name: "Treecko",
    level: 16,
    nature: "Adamant",
    ability: "Unburden",
    item: "Oran Berry",
    move1: "Pow-Up Punch",
    move2: "Bullet Seed",
    move3: "Drain Punch",
    move4: "Rock Tomb",
  },
];

export const viridianForestLassAnneTeam: Pokemon[] = [
  {
    name: "Stufful",
    level: 15,
    nature: "Bashful",
    ability: "Fluffy",
    item: "Oran Berry",
    move1: "Low Sweep",
    move2: "Tackle",
    move3: "Aerial Ace",
  },
  {
    name: "Clefairy",
    level: 13,
    nature: "Bashful",
    ability: "Magic Guard",
    item: "Life Orb",
    move1: "Metronome",
  },
  {
    name: "Audino",
    level: 15,
    nature: "Bashful",
    ability: "Regenerator",
    move1: "Swagger",
    move2: "Protect",
    move3: "Wish",
    move3: "Yawn",
  },
];

export const viridianForestBugCatcherSammyTeam: Pokemon[] = [
  {
    name: "Kricketune",
    level: 13,
    nature: "Bashful",
    ability: "Technician",
    item: "Lum Berry",
    move1: "Bug Bite",
    move2: "Bullet Seed",
    move3: "Bulldoze",
    move4: "Rock Tomb",
  },
  {
    name: "Dustox",
    level: 14,
    nature: "Bold",
    ability: "Shield Dust",
    item: "Black Sludge",
    move1: "Toxic",
    move2: "Protect",
    move3: "Roost",
    move4: "Psybeam",
  },
  {
    name: "Volbeat",
    level: 13,
    nature: "Bashful",
    ability: "Prankster",
    item: "Lum Berry",
    move1: "HP Bug",
    move2: "Mega Drain",
    move3: "Flash",
    move4: "Water Pulse",
  },
];

export const pewterMuseumLeaderFalknerTeam: Pokemon[] = [
  {
    name: "Trumbeak",
    level: 14,
    nature: "Bashful",
    ability: "Skill Link",
    item: "Lum Berry",
    move1: "Flame Charge",
    move2: "Pluck",
    move3: "Bullet Seed",
    move4: "Sleep Talk",
  },
  {
    name: "Wattrel",
    level: 16,
    nature: "Modest",
    ability: "Volt Absorb",
    item: "Berry Juice",
    move1: "Volt Switch",
    move2: "Air Slash",
    move3: "HP Ground",
    move4: "Sleep Talk",
  },
  {
    name: "Yanma",
    level: 13,
    nature: "Bashful",
    ability: "Speed Boost",
    item: "Lum Berry",
    move1: "Mega Drain",
    move2: "Ancient Power",
    move3: "HP Bug",
    move4: "Air Cutter",
  },
  {
    name: "Squawkabilly-G",
    sprite: "squawkabilly",
    pokedex: "Squawkabilly",
    level: 14,
    nature: "Bashful",
    ability: "Hustle",
    item: "Muscle Band",
    move1: "Aerial Ace",
    move2: "Quick Attack",
    move3: "Reversal",
    move4: "Parting Shot",
  },
  {
    name: "Farfetch'd-G",
    sprite: "farfetchd-galar",
    pokedex: "Farfetch\u2019d-Galar",
    level: 14,
    nature: "Bashful",
    ability: "Scrappy",
    item: "Leek",
    move1: "Rock Smash",
    move2: "Slam",
    move3: "Brutal Swing",
    move4: "Roost",
  },
];

export const pewterCityLeaderBrockTeam: Pokemon[] = [
  {
    name: "Hippopotas",
    level: 13,
    nature: "Careful",
    ability: "Sand Stream",
    item: "Berry Juice",
    move1: "Bulldoze",
    move2: "Rock Tomb",
    move3: "Toxic",
    move4: "Slack Off",
  },
  {
    name: "Cacnea",
    level: 15,
    nature: "Bashful",
    ability: "Sand Rush",
    item: "Eviolite",
    move1: "Pow-Up Punch",
    move2: "Bullet Seed",
    move3: "Thunder Punch",
    move4: "Pin Missile",
  },
  {
    name: "Lunatone",
    level: 14,
    nature: "Bashful",
    ability: "Levitate",
    item: "Lum Berry",
    move1: "Ancient Power",
    move2: "Psybeam",
    move3: "HP Ground",
    move4: "Icy Wind",
  },
  {
    name: "Lileep",
    level: 16,
    nature: "Bold",
    ability: "Storm Drain",
    item: "Oran Berry",
    move1: "Stockpile",
    move2: "Recover",
    move3: "HP Rock",
    move4: "Mega Drain",
  },
  {
    name: "Archen",
    level: 14,
    nature: "Bashful",
    ability: "Defeatist",
    item: "Iapapa Berry",
    move1: "Wing Attack",
    move2: "Rock Tomb",
    move3: "Bulldoze",
    move4: "Facade",
  },
  {
    name: "Varoom",
    level: 15,
    nature: "Careful",
    ability: "Filter",
    item: "Air Balloon",
    move1: "Bulldoze",
    move2: "Gyro Ball",
    move3: "Toxic",
    move4: "Protect",
  },
];

export const route3LassSallyTeam: Pokemon[] = [
  {
    name: "Pikachu-Flying",
    sprite: "pikachu",
    level: 21,
    nature: "Naive",
    ability: "Lightning Rod",
    item: "Light Ball",
    move1: "Zippy Zap",
    move2: "HP Flying",
    move3: "Extreme Speed",
    move4: "Grass Knot",
  },
  {
    name: "Oricorio-Sensu",
    level: 22,
    nature: "Timid",
    ability: "Dancer",
    item: "Spell Tag",
    move1: "Calm Mind",
    move2: "Air Cutter",
    move3: "HP Ghost",
    move4: "Roost",
  },
  {
    name: "Whimsicott",
    level: 22,
    nature: "Modest",
    ability: "Prankster",
    item: "Leftovers",
    move1: "Leech Seed",
    move2: "Protect",
    move3: "Mega Drain",
    move4: "HP Psychic",
  },
  {
    name: "Mawile",
    level: 21,
    nature: "Impish",
    ability: "Intimidate",
    item: "Leftovers",
    move1: "Toxic",
    move2: "Covet",
    move3: "Metal Claw",
    move4: "Fire Fang",
  },
];

export const mtMoonSuperNerdMiguelTeam: Pokemon[] = [
  {
    name: "Thwackey",
    level: 21,
    nature: "Adamant",
    ability: "Grassy Surge",
    item: "Eviolite",
    move1: "Fake Out",
    move2: "Grassy Glide",
    move3: "Knock Off",
    move4: "U-Turn",
  },
  {
    name: "Voltorb-H",
    sprite: "voltorb-hisui",
    pokedex: "Voltorb-Hisui",
    level: 22,
    nature: "Naive",
    ability: "Reckless",
    item: "Focus Sash",
    move1: "Mega Drain",
    move2: "Self-Destruct",
    move3: "Volt Switch",
    move4: "HP Ice",
  },
  {
    name: "Swoobat",
    level: 22,
    nature: "Timid",
    ability: "Simple",
    item: "Grassy Seed",
    move1: "Calm Mind",
    move2: "Air Cutter",
    move3: "Psybeam",
    move4: "Roost",
  },
  {
    name: "Skiddo",
    level: 22,
    nature: "Impish",
    ability: "Grass Pelt",
    item: "Miracle Seed",
    move1: "Horn Leech",
    move2: "Brick Break",
    move3: "Rock Slide",
    move4: "Milk Drink",
  },
  {
    name: "Sableye",
    level: 22,
    nature: "Careful",
    ability: "Prankster",
    item: "Leftovers",
    move1: "Will-O-Wisp",
    move2: "Recover",
    move3: "Protect",
    move4: "Foul Play",
  },
];

export const mtMoonArcherTeam: Pokemon[] = [
  {
    name: "Glimmet",
    level: 20,
    nature: "Bashful",
    ability: "Toxic Debris",
    item: "Shuca Berry",
    move1: "Ancient Power",
    move2: "Venoshock",
    move3: "Mud Shot",
    move4: "Protect",
  },
  {
    name: "Seviper",
    level: 21,
    nature: "Bashful",
    ability: "Fatal Precision",
    item: "Shuca Berry",
    move1: "Mega Drain",
    move2: "Poison Fang",
    move3: "Bulldoze",
    move4: "Hypnosis",
  },
  {
    name: "Houndour",
    level: 23,
    nature: "Timid",
    ability: "Flash Fire",
    item: "Focus Sash",
    move1: "Nasty Plot",
    move2: "Incinerate",
    move3: "Snarl",
    move4: "HP Electric",
  },
  {
    name: "Mightyena",
    level: 21,
    nature: "Bashful",
    ability: "Strong Jaw",
    item: "Berry Juice",
    move1: "Bite",
    move2: "Ice Fang",
    move3: "Poison Fang",
    move4: "Howl",
  },
  {
    name: "Fearow",
    level: 20,
    nature: "Bashful",
    ability: "Technician",
    item: "Muscle Band",
    move1: "Pursuit",
    move2: "Pluck",
    move3: "Drill Run",
    move4: "Double Hit",
  },
];

export const ceruleanCityRivalTeam = [
  {
    name: "Hitmonlee",
    level: 27,
    nature: "Jolly",
    ability: "Striker",
    item: "Black Belt",
    move1: "Bullet Punch",
    move2: "Knock Off",
    move3: "Fake Out",
    move4: "Low Sweep",
  },
  {
    name: "Eevee",
    level: 26,
    nature: "Rash",
    ability: "Adaptability",
    item: "Eevium Z",
    move1: "Last Resort",
    move2: "Round",
    move3: "Double Kick",
    move4: "Bite",
  },
  {
    name: "Clefable",
    level: 27,
    nature: "Timid",
    ability: "Magic Guard",
    item: "Life Orb",
    move1: "Charge Beam",
    move2: "Draining Kiss",
    move3: "Icy Wind",
    move4: "Mystical Fire",
  },
  {
    name: "Simisear",
    level: 27,
    nature: "Timid",
    ability: "Sage Power",
    item: "Charcoal",
    move1: "Incinerate",
    move2: "Grass Knot",
    move3: "HP Rock",
    move4: "Sleep Talk",
  },
  {
    name: "Arbok",
    level: 28,
    nature: "Jolly",
    ability: "Intimidate",
    item: "Poison Barb",
    move1: "Poison Jab",
    move2: "Sucker Punch",
    move3: "Crunch",
    move4: "Thunder Fang",
  },
  {
    name: "Wartortle",
    level: 28,
    nature: "Modest",
    ability: "Torrent",
    item: "Eviolite",
    move1: "Shell Smash",
    move2: "Water Pulse",
    move3: "Icy Wind",
    move4: "HP Electric",
  },
];

export const nuggetBridgeBugCatcherCaleTeam: Pokemon[] = [
  {
    name: "Vivillon",
    level: 25,
    nature: "Bashful",
    ability: "Friend Guard",
    item: "Charti Berry",
    move1: "Struggle Bug",
    move2: "Electroweb",
    move3: "Air Cutter",
    move4: "Draining Kiss",
  },
  {
    name: "Butterfree",
    level: 26,
    nature: "Timid",
    ability: "Compound Eyes",
    item: "Sitrus Berry",
    move1: "Sleep Powder",
    move2: "Mega Drain",
    move3: "Air Cutter",
    move4: "Bug Buzz",
  },
  {
    name: "Wormadam-Sa",
    sprite: "wormadam-sandy",
    pokedex: "Wormadam-Sandy",
    level: 26,
    nature: "Careful",
    ability: "Overcoat",
    item: "Rocky Helmet",
    move1: "Bulldoze",
    move2: "Bug Bite",
    move3: "Rock Tomb",
    move4: "Sucker Punch",
  },
];

export const nuggetBridgeLassAliTeam: Pokemon[] = [
  {
    name: "Jigglypuff",
    level: 27,
    nature: "Bold",
    ability: "Friend Guard",
    item: "Eviolite",
    move1: "Round",
    move2: "Draining Kiss",
    move3: "Incinerate",
    move4: "Icy Wind",
  },
  {
    name: "Amaura",
    level: 26,
    nature: "Modest",
    ability: "Refrigerate",
    item: "Chople Berry",
    move1: "Round",
    move2: "Ancient Power",
    move3: "Water Pulse",
    move4: "Mud Shot",
  },
  {
    name: "Brionne",
    level: 26,
    nature: "Bashful",
    ability: "Liquid Voice",
    item: "Sitrus Berry",
    move1: "Round",
    move2: "Draining Kiss",
    move3: "Icy Wind",
    move4: "Aqua Jet",
  },
];

export const nuggetBridgeYoungsterTimmyTeam: Pokemon[] = [
  {
    name: "Plusle",
    level: 26,
    nature: "Timid",
    ability: "Plus",
    item: "Shuca Berry",
    move1: "Grass Knot",
    move2: "Electroweb",
    move3: "Signal Beam",
    move4: "Charge Beam",
  },
  {
    name: "Electrike",
    level: 26,
    nature: "Timid",
    ability: "Minus",
    item: "Magnet",
    move1: "Shock Wave",
    move2: "Round",
    move3: "Flame Burst",
    move4: "Signal Beam",
  },
  {
    name: "Snover",
    level: 26,
    nature: "Bashful",
    ability: "Ice Body",
    item: "Occa Berry",
    move1: "Ice Shard",
    move2: "Mega Drain",
    move3: "Icicle Crash",
    move4: "Water Pulse",
  },
];

export const nuggetBridgeLassReliTeam: Pokemon[] = [
  {
    name: "Greedent",
    level: 26,
    nature: "Bashful",
    ability: "Cheek Pouch",
    item: "Sitrus Berry",
    move1: "Stom. Tantrum",
    move2: "Facade",
    move3: "Seed Bomb",
    move4: "Swords Dance",
  },
  {
    name: "Togetic",
    level: 25,
    nature: "Bashful",
    ability: "Serene Grace",
    item: "Eviolite",
    move1: "Air Slash",
    move2: "Thunder Wave",
    move3: "Draining Kiss",
    move4: "Magical Leaf",
  },
  {
    name: "Clamperl",
    level: 26,
    nature: "Modest",
    ability: "Battle Armor",
    item: "Deep Sea Tooth",
    move1: "Water Pulse",
    move2: "Icy Wind",
    move3: "Rest",
    move4: "Sleep Talk",
  },
];

export const nuggetBridgeCamperEthanTeam: Pokemon[] = [
  {
    name: "Mabosstiff",
    level: 26,
    nature: "Adamant",
    ability: "Intimidate",
    item: "Black Glasses",
    move1: "Trailblaze",
    move2: "Bite",
    move3: "Fire Fang",
    move4: "Ice Fang",
  },
  {
    name: "Salandit",
    level: 26,
    nature: "Timid",
    ability: "Corrosion",
    item: "Black Sludge",
    move1: "Toxic",
    move2: "Substitute",
    move3: "Protect",
    move4: "Incinerate",
  },
  {
    name: "Misdreavus",
    level: 26,
    nature: "Bashful",
    ability: "Levitate",
    item: "Eviolite",
    move1: "Hex",
    move2: "Will-O-Wisp",
    move3: "Icy Wind",
    move4: "Shock Wave",
  },
];

export const nuggetBridgeGruntTeam: Pokemon[] = [
  {
    name: "Arcanine",
    level: 26,
    nature: "Jolly",
    ability: "Intimidate",
    item: "Sitrus Berry",
    move1: "Dragon Rage",
    move2: "Flame Wheel",
    move3: "Thunder Fang",
    move4: "Bulldoze",
  },
  {
    name: "Druddigon",
    level: 28,
    nature: "Impish",
    ability: "Rough Skin",
    item: "Leftovers",
    move1: "Toxic",
    move2: "Protect",
    move3: "Dragon Tail",
    move4: "Poison Tail",
  },
  {
    name: "Togedemaru",
    level: 27,
    nature: "Careful",
    ability: "Iron Barbs",
    item: "Rocky Helmet",
    move1: "U-Turn",
    move2: "Zippy Zap",
    move3: "Iron Head",
    move4: "Nuzzle",
  },
  {
    name: "Komala",
    level: 28,
    nature: "Adamant",
    ability: "Comatose",
    item: "Silk Scarf",
    move1: "Sleep Talk",
    move2: "Last Resort",
  },
];

export const digHouseGruntTeam: Pokemon[] = [
  {
    name: "Persian-A",
    sprite: "persian-alola",
    pokedex: "Persian-Alola",
    level: 26,
    nature: "Timid",
    ability: "Feline Prowess",
    item: "Black Glasses",
    move1: "Dark Pulse",
    move2: "Water Pulse",
    move3: "Parting Shot",
    move4: "Shock Wave",
  },
  {
    name: "Crobat",
    level: 26,
    nature: "Naive",
    ability: "Sniper",
    item: "Scope Lens",
    move1: "Mega Drain",
    move2: "Cross Poison",
    move3: "Air Cutter",
    move4: "HP Fire",
  },
  {
    name: "Raticate",
    level: 27,
    nature: "Jolly",
    ability: "Guts",
    item: "Flame Orb",
    move1: "Facade",
    move2: "Stom. Tantrum",
    move3: "Sucker Punch",
    move4: "U-Turn",
  },
  {
    name: "Veluza",
    level: 25,
    nature: "Jolly",
    ability: "Sharpness",
    item: "Expert Belt",
    move1: "Aqua Cutter",
    move2: "Psycho Cut",
    move3: "Aqua Jet",
    move4: "Crunch",
  },
];

export const ceruleanCityLeaderMistyTeam: Pokemon[] = [
  {
    name: "Politoed",
    level: 27,
    nature: "Sassy",
    ability: "Drizzle",
    item: "Iapapa Berry",
    move1: "Flip Turn",
    move2: "Scald",
    move3: "Earthquake",
    move4: "Toxic",
  },
  {
    name: "Ludicolo",
    level: 28,
    nature: "Mild",
    ability: "Swift Swim",
    item: "Sitrus Berry",
    move1: "Giga Drain",
    move2: "Scald",
    move3: "Aurora Beam",
    move4: "Thunder Punch",
  },
  {
    name: "Mantine",
    level: 27,
    nature: "Modest",
    ability: "Swift Swim",
    item: "Wacan Berry",
    move1: "Scald",
    move2: "Hurricane",
    move3: "Roost",
    move4: "HP Grass",
  },
  {
    name: "Clodsire",
    level: 28,
    nature: "Careful",
    ability: "Water Absorb",
    item: "Black Sludge",
    move1: "Poison Jab",
    move2: "Bulldoze",
    move3: "Recover",
    move4: "Toxic",
  },
  {
    name: "Starmie",
    level: 28,
    nature: "Modest",
    ability: "Analytic",
    item: "Mystic Water",
    move1: "Scald",
    move2: "Thunderbolt",
    move3: "Psyshock",
    move4: "Aurora Beam",
  },
  {
    name: "Toxicroak",
    level: 27,
    nature: "Jolly",
    ability: "Dry Skin",
    item: "Life Orb",
    move1: "Swords Dance",
    move2: "Drain Punch",
    move3: "Poison Jab",
    move4: "Sucker Punch",
  },
];
