import { createBox } from "@site/src/utils/box";

export const route22RivalBox = createBox([
  {
    name: "Snubbull",
    level: 15,
    nature: "Adamant",
    ability: "Intimidate",
    item: "Muscle Band",
    moves: ["Pow-Up Punch", "Covet", "Thunder Wave", "Fire Fang"],
  },
  {
    name: "Litleo",
    level: 15,
    nature: "Timid",
    ability: "Rivalry",
    item: "Wise Glasses",
    moves: ["Incinerate", "Round", "HP Grass", "Sleep Talk"],
  },
  {
    name: "Squirtle",
    level: 16,
    nature: "Adamant",
    ability: "Torrent",
    item: "Oran Berry",
    moves: ["Pow-Up Punch", "Aqua Jet", "Rock Tomb", "Curse"],
  },
]);

export const viridianForestBrendanBox = createBox([
  {
    name: "Meditite",
    level: 14,
    nature: "Adamant",
    ability: "Pure Power",
    item: "Muscle Band",
    moves: ["Fake Out", "Rock Smash", "Bullet Punch", "Rock Tomb"],
  },
  {
    name: "Corphish",
    level: 15,
    nature: "Adamant",
    ability: "Adaptability",
    item: "Mystic Water",
    moves: ["Aqua Jet", "Aerial Ace", "Rock Tomb", "Knock Off"],
  },
  {
    name: "Numel",
    level: 15,
    nature: "Lonely",
    ability: "Simple",
    item: "Passho Berry",
    moves: ["Ancient Power", "Flame Charge", "Rock Tomb", "Bulldoze"],
  },
  {
    name: "Treecko",
    level: 16,
    nature: "Adamant",
    ability: "Unburden",
    item: "Oran Berry",
    moves: ["Pow-Up Punch", "Bullet Seed", "Drain Punch", "Rock Tomb"],
  },
]);

export const viridianForestLassAnneBox = createBox([
  {
    name: "Stufful",
    level: 15,
    nature: "Bashful",
    ability: "Fluffy",
    item: "Oran Berry",
    moves: ["Low Sweep", "Tackle", "Aerial Ace"],
  },
  {
    name: "Clefairy",
    level: 13,
    nature: "Bashful",
    ability: "Magic Guard",
    item: "Life Orb",
    moves: ["Metronome"],
  },
  {
    name: "Audino",
    level: 15,
    nature: "Bashful",
    ability: "Regenerator",
    moves: ["Swagger", "Protect", "Wish", "Yawn"],
  },
]);

export const viridianForestBugCatcherSammyBox = createBox([
  {
    name: "Kricketune",
    level: 13,
    nature: "Bashful",
    ability: "Technician",
    item: "Lum Berry",
    moves: ["Bug Bite", "Bullet Seed", "Bulldoze", "Rock Tomb"],
  },
  {
    name: "Dustox",
    level: 14,
    nature: "Bold",
    ability: "Shield Dust",
    item: "Black Sludge",
    moves: ["Toxic", "Protect", "Roost", "Psybeam"],
  },
  {
    name: "Volbeat",
    level: 13,
    nature: "Bashful",
    ability: "Prankster",
    item: "Lum Berry",
    moves: ["HP Bug", "Mega Drain", "Flash", "Water Pulse"],
  },
]);

export const pewterMuseumLeaderFalknerBox = createBox([
  {
    name: "Trumbeak",
    level: 14,
    nature: "Bashful",
    ability: "Skill Link",
    item: "Lum Berry",
    moves: ["Flame Charge", "Pluck", "Bullet Seed", "Sleep Talk"],
  },
  {
    name: "Wattrel",
    level: 16,
    nature: "Modest",
    ability: "Volt Absorb",
    item: "Berry Juice",
    moves: ["Volt Switch", "Air Slash", "HP Ground", "Sleep Talk"],
  },
  {
    name: "Yanma",
    level: 13,
    nature: "Bashful",
    ability: "Speed Boost",
    item: "Lum Berry",
    moves: ["Mega Drain", "Ancient Power", "HP Bug", "Air Cutter"],
  },
  {
    name: "Squawkabilly-G",
    spriteKey: "squawkabilly",
    pokedexKey: "Squawkabilly",
    level: 14,
    nature: "Bashful",
    ability: "Hustle",
    item: "Muscle Band",
    moves: ["Aerial Ace", "Quick Attack", "Reversal", "Parting Shot"],
  },
  {
    name: "Farfetch'd-G",
    spriteKey: "farfetchd-galar",
    pokedexKey: "Farfetch\u2019d-Galar",
    level: 14,
    nature: "Bashful",
    ability: "Scrappy",
    item: "Leek",
    moves: ["Rock Smash", "Slam", "Brutal Swing", "Roost"],
  },
]);

export const pewterCityLeaderBrockBox = createBox([
  {
    name: "Hippopotas",
    level: 13,
    nature: "Careful",
    ability: "Sand Stream",
    item: "Berry Juice",
    moves: ["Bulldoze", "Rock Tomb", "Toxic", "Slack Off"],
  },
  {
    name: "Cacnea",
    level: 15,
    nature: "Bashful",
    ability: "Sand Rush",
    item: "Eviolite",
    moves: ["Pow-Up Punch", "Bullet Seed", "Thunder Punch", "Pin Missile"],
  },
  {
    name: "Lunatone",
    level: 14,
    nature: "Bashful",
    ability: "Levitate",
    item: "Lum Berry",
    moves: ["Ancient Power", "Psybeam", "HP Ground", "Icy Wind"],
  },
  {
    name: "Lileep",
    level: 16,
    nature: "Bold",
    ability: "Storm Drain",
    item: "Oran Berry",
    moves: ["Stockpile", "Recover", "HP Rock", "Mega Drain"],
  },
  {
    name: "Archen",
    level: 14,
    nature: "Bashful",
    ability: "Defeatist",
    item: "Iapapa Berry",
    moves: ["Wing Attack", "Rock Tomb", "Bulldoze", "Facade"],
  },
  {
    name: "Varoom",
    level: 15,
    nature: "Careful",
    ability: "Filter",
    item: "Air Balloon",
    moves: ["Bulldoze", "Gyro Ball", "Toxic", "Protect"],
  },
]);

export const route3LassSallyBox = createBox([
  {
    name: "Pikachu-Flying",
    spriteKey: "pikachu",
    level: 21,
    nature: "Naive",
    ability: "Lightning Rod",
    item: "Light Ball",
    moves: ["Zippy Zap", "HP Flying", "Extreme Speed", "Grass Knot"],
  },
  {
    name: "Oricorio-Sensu",
    level: 22,
    nature: "Timid",
    ability: "Dancer",
    item: "Spell Tag",
    moves: ["Calm Mind", "Air Cutter", "HP Ghost", "Roost"],
  },
  {
    name: "Whimsicott",
    level: 22,
    nature: "Modest",
    ability: "Prankster",
    item: "Leftovers",
    moves: ["Leech Seed", "Protect", "Mega Drain", "HP Psychic"],
  },
  {
    name: "Mawile",
    level: 21,
    nature: "Impish",
    ability: "Intimidate",
    item: "Leftovers",
    moves: ["Toxic", "Covet", "Metal Claw", "Fire Fang"],
  },
]);

export const mtMoonSuperNerdMiguelBox = createBox([
  {
    name: "Thwackey",
    level: 21,
    nature: "Adamant",
    ability: "Grassy Surge",
    item: "Eviolite",
    moves: ["Fake Out", "Grassy Glide", "Knock Off", "U-Turn"],
  },
  {
    name: "Voltorb-H",
    spriteKey: "voltorb-hisui",
    pokedexKey: "Voltorb-Hisui",
    level: 22,
    nature: "Naive",
    ability: "Reckless",
    item: "Focus Sash",
    moves: ["Mega Drain", "Self-Destruct", "Volt Switch", "HP Ice"],
  },
  {
    name: "Swoobat",
    level: 22,
    nature: "Timid",
    ability: "Simple",
    item: "Grassy Seed",
    moves: ["Calm Mind", "Air Cutter", "Psybeam", "Roost"],
  },
  {
    name: "Skiddo",
    level: 22,
    nature: "Impish",
    ability: "Grass Pelt",
    item: "Miracle Seed",
    moves: ["Horn Leech", "Brick Break", "Rock Slide", "Milk Drink"],
  },
  {
    name: "Sableye",
    level: 22,
    nature: "Careful",
    ability: "Prankster",
    item: "Leftovers",
    moves: ["Will-O-Wisp", "Recover", "Protect", "Foul Play"],
  },
]);

export const mtMoonArcherBox = createBox([
  {
    name: "Glimmet",
    level: 20,
    nature: "Bashful",
    ability: "Toxic Debris",
    item: "Shuca Berry",
    moves: ["Ancient Power", "Venoshock", "Mud Shot", "Protect"],
  },
  {
    name: "Seviper",
    level: 21,
    nature: "Bashful",
    ability: "Fatal Precision",
    item: "Shuca Berry",
    moves: ["Mega Drain", "Poison Fang", "Bulldoze", "Hypnosis"],
  },
  {
    name: "Houndour",
    level: 23,
    nature: "Timid",
    ability: "Flash Fire",
    item: "Focus Sash",
    moves: ["Nasty Plot", "Incinerate", "Snarl", "HP Electric"],
  },
  {
    name: "Mightyena",
    level: 21,
    nature: "Bashful",
    ability: "Strong Jaw",
    item: "Berry Juice",
    moves: ["Bite", "Ice Fang", "Poison Fang", "Howl"],
  },
  {
    name: "Fearow",
    level: 20,
    nature: "Bashful",
    ability: "Technician",
    item: "Muscle Band",
    moves: ["Pursuit", "Pluck", "Drill Run", "Double Hit"],
  },
]);

export const ceruleanCityRivalBox = createBox([
  {
    name: "Hitmonlee",
    level: 27,
    nature: "Jolly",
    ability: "Striker",
    item: "Black Belt",
    moves: ["Bullet Punch", "Knock Off", "Fake Out", "Low Sweep"],
  },
  {
    name: "Eevee",
    level: 26,
    nature: "Rash",
    ability: "Adaptability",
    item: "Eevium Z",
    moves: ["Last Resort", "Round", "Double Kick", "Bite"],
  },
  {
    name: "Clefable",
    level: 27,
    nature: "Timid",
    ability: "Magic Guard",
    item: "Life Orb",
    moves: ["Charge Beam", "Draining Kiss", "Icy Wind", "Mystical Fire"],
  },
  {
    name: "Simisear",
    level: 27,
    nature: "Timid",
    ability: "Sage Power",
    item: "Charcoal",
    moves: ["Incinerate", "Grass Knot", "HP Rock", "Sleep Talk"],
  },
  {
    name: "Arbok",
    level: 28,
    nature: "Jolly",
    ability: "Intimidate",
    item: "Poison Barb",
    moves: ["Poison Jab", "Sucker Punch", "Crunch", "Thunder Fang"],
  },
  {
    name: "Wartortle",
    level: 28,
    nature: "Modest",
    ability: "Torrent",
    item: "Eviolite",
    moves: ["Shell Smash", "Water Pulse", "Icy Wind", "HP Electric"],
  },
]);

export const nuggetBridgeBugCatcherCaleBox = createBox([
  {
    name: "Vivillon",
    level: 25,
    nature: "Bashful",
    ability: "Friend Guard",
    item: "Charti Berry",
    moves: ["Struggle Bug", "Electroweb", "Air Cutter", "Draining Kiss"],
  },
  {
    name: "Butterfree",
    level: 26,
    nature: "Timid",
    ability: "Compound Eyes",
    item: "Sitrus Berry",
    moves: ["Sleep Powder", "Mega Drain", "Air Cutter", "Bug Buzz"],
  },
  {
    name: "Wormadam-Sa",
    spriteKey: "wormadam-sandy",
    pokedexKey: "Wormadam-Sandy",
    level: 26,
    nature: "Careful",
    ability: "Overcoat",
    item: "Rocky Helmet",
    moves: ["Bulldoze", "Bug Bite", "Rock Tomb", "Sucker Punch"],
  },
]);

export const nuggetBridgeLassAliBox = createBox([
  {
    name: "Jigglypuff",
    level: 27,
    nature: "Bold",
    ability: "Friend Guard",
    item: "Eviolite",
    moves: ["Round", "Draining Kiss", "Incinerate", "Icy Wind"],
  },
  {
    name: "Amaura",
    level: 26,
    nature: "Modest",
    ability: "Refrigerate",
    item: "Chople Berry",
    moves: ["Round", "Ancient Power", "Water Pulse", "Mud Shot"],
  },
  {
    name: "Brionne",
    level: 26,
    nature: "Bashful",
    ability: "Liquid Voice",
    item: "Sitrus Berry",
    moves: ["Round", "Draining Kiss", "Icy Wind", "Aqua Jet"],
  },
]);

export const nuggetBridgeYoungsterTimmyBox = createBox([
  {
    name: "Plusle",
    level: 26,
    nature: "Timid",
    ability: "Plus",
    item: "Shuca Berry",
    moves: ["Grass Knot", "Electroweb", "Signal Beam", "Charge Beam"],
  },
  {
    name: "Electrike",
    level: 26,
    nature: "Timid",
    ability: "Minus",
    item: "Magnet",
    moves: ["Shock Wave", "Round", "Flame Burst", "Signal Beam"],
  },
  {
    name: "Snover",
    level: 26,
    nature: "Bashful",
    ability: "Ice Body",
    item: "Occa Berry",
    moves: ["Ice Shard", "Mega Drain", "Icicle Crash", "Water Pulse"],
  },
]);

export const nuggetBridgeLassReliBox = createBox([
  {
    name: "Greedent",
    level: 26,
    nature: "Bashful",
    ability: "Cheek Pouch",
    item: "Sitrus Berry",
    moves: ["Stom. Tantrum", "Facade", "Seed Bomb", "Swords Dance"],
  },
  {
    name: "Togetic",
    level: 25,
    nature: "Bashful",
    ability: "Serene Grace",
    item: "Eviolite",
    moves: ["Air Slash", "Thunder Wave", "Draining Kiss", "Magical Leaf"],
  },
  {
    name: "Clamperl",
    level: 26,
    nature: "Modest",
    ability: "Battle Armor",
    item: "Deep Sea Tooth",
    moves: ["Water Pulse", "Icy Wind", "Rest", "Sleep Talk"],
  },
]);

export const nuggetBridgeCamperEthanBox = createBox([
  {
    name: "Mabosstiff",
    level: 26,
    nature: "Adamant",
    ability: "Intimidate",
    item: "Black Glasses",
    moves: ["Trailblaze", "Bite", "Fire Fang", "Ice Fang"],
  },
  {
    name: "Salandit",
    level: 26,
    nature: "Timid",
    ability: "Corrosion",
    item: "Black Sludge",
    moves: ["Toxic", "Substitute", "Protect", "Incinerate"],
  },
  {
    name: "Misdreavus",
    level: 26,
    nature: "Bashful",
    ability: "Levitate",
    item: "Eviolite",
    moves: ["Hex", "Will-O-Wisp", "Icy Wind", "Shock Wave"],
  },
]);

export const nuggetBridgeGruntBox = createBox([
  {
    name: "Arcanine",
    level: 26,
    nature: "Jolly",
    ability: "Intimidate",
    item: "Sitrus Berry",
    moves: ["Dragon Rage", "Flame Wheel", "Thunder Fang", "Bulldoze"],
  },
  {
    name: "Druddigon",
    level: 28,
    nature: "Impish",
    ability: "Rough Skin",
    item: "Leftovers",
    moves: ["Toxic", "Protect", "Dragon Tail", "Poison Tail"],
  },
  {
    name: "Togedemaru",
    level: 27,
    nature: "Careful",
    ability: "Iron Barbs",
    item: "Rocky Helmet",
    moves: ["U-Turn", "Zippy Zap", "Iron Head", "Nuzzle"],
  },
  {
    name: "Komala",
    level: 28,
    nature: "Adamant",
    ability: "Comatose",
    item: "Silk Scarf",
    moves: ["Sleep Talk", "Last Resort"],
  },
]);

export const digHouseGruntBox = createBox([
  {
    name: "Persian-A",
    spriteKey: "persian-alola",
    pokedexKey: "Persian-Alola",
    level: 26,
    nature: "Timid",
    ability: "Feline Prowess",
    item: "Black Glasses",
    moves: ["Dark Pulse", "Water Pulse", "Parting Shot", "Shock Wave"],
  },
  {
    name: "Crobat",
    level: 26,
    nature: "Naive",
    ability: "Sniper",
    item: "Scope Lens",
    moves: ["Mega Drain", "Cross Poison", "Air Cutter", "HP Fire"],
  },
  {
    name: "Raticate",
    level: 27,
    nature: "Jolly",
    ability: "Guts",
    item: "Flame Orb",
    moves: ["Facade", "Stom. Tantrum", "Sucker Punch", "U-Turn"],
  },
  {
    name: "Veluza",
    level: 25,
    nature: "Jolly",
    ability: "Sharpness",
    item: "Expert Belt",
    moves: ["Aqua Cutter", "Psycho Cut", "Aqua Jet", "Crunch"],
  },
]);

export const ceruleanCityLeaderMistyBox = createBox([
  {
    name: "Politoed",
    level: 27,
    nature: "Sassy",
    ability: "Drizzle",
    item: "Iapapa Berry",
    moves: ["Flip Turn", "Scald", "Earthquake", "Toxic"],
  },
  {
    name: "Ludicolo",
    level: 28,
    nature: "Mild",
    ability: "Swift Swim",
    item: "Sitrus Berry",
    moves: ["Giga Drain", "Scald", "Aurora Beam", "Thunder Punch"],
  },
  {
    name: "Mantine",
    level: 27,
    nature: "Modest",
    ability: "Swift Swim",
    item: "Wacan Berry",
    moves: ["Scald", "Hurricane", "Roost", "HP Grass"],
  },
  {
    name: "Clodsire",
    level: 28,
    nature: "Careful",
    ability: "Water Absorb",
    item: "Black Sludge",
    moves: ["Poison Jab", "Bulldoze", "Recover", "Toxic"],
  },
  {
    name: "Starmie",
    level: 28,
    nature: "Modest",
    ability: "Analytic",
    item: "Mystic Water",
    moves: ["Scald", "Thunderbolt", "Psyshock", "Aurora Beam"],
  },
  {
    name: "Toxicroak",
    level: 27,
    nature: "Jolly",
    ability: "Dry Skin",
    item: "Life Orb",
    moves: ["Swords Dance", "Drain Punch", "Poison Jab", "Sucker Punch"],
  },
]);
